#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/java/xlOverlay_java
  
  rm -rf xlattice/overlays/store/* 
  
  pySloc -L java   -X target -v $@
else
  echo "DEV_BASE is not defined"
fi
